
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_DETERMINISTIC_INFORMED_ASTAR_STATIC_WEIGHTED_A_STAR_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_DETERMINISTIC_INFORMED_ASTAR_STATIC_WEIGHTED_A_STAR_HPP

class StaticWeightedAStar {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_DETERMINISTIC_INFORMED_ASTAR_STATIC_WEIGHTED_A_STAR_HPP
