
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_DETERMINISTIC_INFORMED_ASTAR_WEIGHTED_GREEDY_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_DETERMINISTIC_INFORMED_ASTAR_WEIGHTED_GREEDY_HPP

class WeightedGreedy {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_DETERMINISTIC_INFORMED_ASTAR_WEIGHTED_GREEDY_HPP
