
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_FOURIER_FOURIER_BASIS_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_FOURIER_FOURIER_BASIS_HPP

class FourierBasis {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_FOURIER_FOURIER_BASIS_HPP
