
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_FOURIER_FOURIER_BASIS_LEARNING_RATE_WRAPPER_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_FOURIER_FOURIER_BASIS_LEARNING_RATE_WRAPPER_HPP

class FourierBasisLearningRateWrapper {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_FOURIER_FOURIER_BASIS_LEARNING_RATE_WRAPPER_HPP
