
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_GAME_EPISODE_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_GAME_EPISODE_HPP

class GameEpisode {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_GAME_EPISODE_HPP
