
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_JOINT_POLICY_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_JOINT_POLICY_HPP

class JointPolicy {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_JOINT_POLICY_HPP
