
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_STOCHASTIC_DPOPERATOR_SOFTMAX_OPERATOR_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_STOCHASTIC_DPOPERATOR_SOFTMAX_OPERATOR_HPP

class SoftmaxOperator {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_STOCHASTIC_DPOPERATOR_SOFTMAX_OPERATOR_HPP
