
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_AUXILIARY_PERFORMANCE_AGENT_FACTORY_AND_TYPE_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_AUXILIARY_PERFORMANCE_AGENT_FACTORY_AND_TYPE_HPP

class AgentFactoryAndType {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_AUXILIARY_PERFORMANCE_AGENT_FACTORY_AND_TYPE_HPP
