
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_AUXILIARY_PERFORMANCE_MULTI_AGENT_EXPERIMENTER_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_AUXILIARY_PERFORMANCE_MULTI_AGENT_EXPERIMENTER_HPP

class MultiAgentExperimenter {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_AUXILIARY_PERFORMANCE_MULTI_AGENT_EXPERIMENTER_HPP
