
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_BLOCKDUDE_STATE_BLOCK_DUDE_MAP_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_BLOCKDUDE_STATE_BLOCK_DUDE_MAP_HPP

class BlockDudeMap {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_BLOCKDUDE_STATE_BLOCK_DUDE_MAP_HPP
