
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_BLOCKDUDE_STATE_BLOCK_DUDE_STATE_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_BLOCKDUDE_STATE_BLOCK_DUDE_STATE_HPP

class BlockDudeState {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_BLOCKDUDE_STATE_BLOCK_DUDE_STATE_HPP
