
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_FROSTBITE_STATE_FROSTBITE_STATE_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_FROSTBITE_STATE_FROSTBITE_STATE_HPP

class FrostbiteState {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_FROSTBITE_STATE_FROSTBITE_STATE_HPP
