
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_FROSTBITE_STATE_FROSTBITE_IGLOO_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_FROSTBITE_STATE_FROSTBITE_IGLOO_HPP

class FrostbiteIgloo {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_FROSTBITE_STATE_FROSTBITE_IGLOO_HPP
