
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_FROSTBITE_STATE_FROSTBITE_PLATFORM_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_FROSTBITE_STATE_FROSTBITE_PLATFORM_HPP

class FrostbitePlatform {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_FROSTBITE_STATE_FROSTBITE_PLATFORM_HPP
