
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_OO_OOSG_DOMAIN_HPP
#define FASTRL_MDP_STOCHASTICGAMES_OO_OOSG_DOMAIN_HPP

class OOSGDomain {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_OO_OOSG_DOMAIN_HPP
