
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_MODELLEARNING_RMAX_POTENTIAL_SHAPED_R_MAX_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_MODELLEARNING_RMAX_POTENTIAL_SHAPED_R_MAX_HPP

class PotentialShapedRMax {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_MODELLEARNING_RMAX_POTENTIAL_SHAPED_R_MAX_HPP
