
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_MODELLEARNING_RMAX_R_MAX_MODEL_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_MODELLEARNING_RMAX_R_MAX_MODEL_HPP

class RMaxModel {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_MODELLEARNING_RMAX_R_MAX_MODEL_HPP
