
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_MODELLEARNING_RMAX_UNMODELED_FAVORED_POLICY_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_MODELLEARNING_RMAX_UNMODELED_FAVORED_POLICY_HPP

class UnmodeledFavoredPolicy {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_MODELLEARNING_RMAX_UNMODELED_FAVORED_POLICY_HPP
