
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_MAQL_MULTI_AGENT_Q_LEARNING_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_MAQL_MULTI_AGENT_Q_LEARNING_HPP

class MultiAgentQLearning {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_MAQL_MULTI_AGENT_Q_LEARNING_HPP
