
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_TOURNAMENT_COMMON_ALL_PAIR_WISE_SAME_TYPE_MS_HPP
#define FASTRL_MDP_STOCHASTICGAMES_TOURNAMENT_COMMON_ALL_PAIR_WISE_SAME_TYPE_MS_HPP

class AllPairWiseSameTypeMS {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_TOURNAMENT_COMMON_ALL_PAIR_WISE_SAME_TYPE_MS_HPP
