
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_TOURNAMENT_COMMON_CONSTANT_WORLD_GENERATOR_HPP
#define FASTRL_MDP_STOCHASTICGAMES_TOURNAMENT_COMMON_CONSTANT_WORLD_GENERATOR_HPP

class ConstantWorldGenerator {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_TOURNAMENT_COMMON_CONSTANT_WORLD_GENERATOR_HPP
