
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_FROSTBITE_FROSTBITE_RF_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_FROSTBITE_FROSTBITE_RF_HPP

class FrostbiteRF {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_FROSTBITE_FROSTBITE_RF_HPP
