
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_CORE_OO_STATE_GENERIC_GENERIC_OO_STATE_HPP
#define FASTRL_MDP_CORE_OO_STATE_GENERIC_GENERIC_OO_STATE_HPP

class GenericOOState {

};

#endif //FASTRL_MDP_CORE_OO_STATE_GENERIC_GENERIC_OO_STATE_HPP
