
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_STOCHASTICGAMES_NORMALFORM_SINGLE_STAGE_NORMAL_FORM_GAME_HPP
#define FASTRL_DOMAIN_STOCHASTICGAMES_NORMALFORM_SINGLE_STAGE_NORMAL_FORM_GAME_HPP

class SingleStageNormalFormGame {

};

#endif //FASTRL_DOMAIN_STOCHASTICGAMES_NORMALFORM_SINGLE_STAGE_NORMAL_FORM_GAME_HPP
