
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_ACTORCRITIC_ACTOR_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_ACTORCRITIC_ACTOR_HPP

class Actor {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_ACTORCRITIC_ACTOR_HPP
