
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_ACTORCRITIC_CRITIC_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_ACTORCRITIC_CRITIC_HPP

class Critic {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_ACTORCRITIC_CRITIC_HPP
