
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_VALUEFUNCTIONVIS_COMMON_LANDMARK_COLOR_BLEND_INTERPOLATION_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_VALUEFUNCTIONVIS_COMMON_LANDMARK_COLOR_BLEND_INTERPOLATION_HPP

class LandmarkColorBlendInterpolation {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_VALUEFUNCTIONVIS_COMMON_LANDMARK_COLOR_BLEND_INTERPOLATION_HPP
