
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_TWOPLAYER_SINGLESTAGE_EQUILIBRIUMPLAYER_EQUILIBRIUMSOLVERS_MIN_MAX_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_TWOPLAYER_SINGLESTAGE_EQUILIBRIUMPLAYER_EQUILIBRIUMSOLVERS_MIN_MAX_HPP

class MinMax {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_TWOPLAYER_SINGLESTAGE_EQUILIBRIUMPLAYER_EQUILIBRIUMSOLVERS_MIN_MAX_HPP
