
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_CUSTOM_REWARD_MODEL_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_CUSTOM_REWARD_MODEL_HPP

class CustomRewardModel {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_CUSTOM_REWARD_MODEL_HPP
