
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_IRL_REQUEST_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_IRL_REQUEST_HPP

class IRLRequest {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_IRL_REQUEST_HPP
