
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_REWARD_VALUE_PROJECTION_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_REWARD_VALUE_PROJECTION_HPP

class RewardValueProjection {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_REWARD_VALUE_PROJECTION_HPP
