
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_MADYNAMICPROGRAMMING_Q_SOURCE_FOR_SINGLE_AGENT_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_MADYNAMICPROGRAMMING_Q_SOURCE_FOR_SINGLE_AGENT_HPP

class QSourceForSingleAgent {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_MADYNAMICPROGRAMMING_Q_SOURCE_FOR_SINGLE_AGENT_HPP
