
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_MADYNAMICPROGRAMMING_SG_BACKUP_OPERATOR_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_MADYNAMICPROGRAMMING_SG_BACKUP_OPERATOR_HPP

class SGBackupOperator {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_MADYNAMICPROGRAMMING_SG_BACKUP_OPERATOR_HPP
