
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_STATEHASHING_WRAPPED_HASHABLE_STATE_HPP
#define FASTRL_STATEHASHING_WRAPPED_HASHABLE_STATE_HPP

class WrappedHashableState {

};

#endif //FASTRL_STATEHASHING_WRAPPED_HASHABLE_STATE_HPP
