
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_SINGLEAGENT_POMDP_BELIEF_AGENT_HPP
#define FASTRL_MDP_SINGLEAGENT_POMDP_BELIEF_AGENT_HPP

class BeliefAgent {

};

#endif //FASTRL_MDP_SINGLEAGENT_POMDP_BELIEF_AGENT_HPP
