
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_AGENT_SG_AGENT_BASE_HPP
#define FASTRL_MDP_STOCHASTICGAMES_AGENT_SG_AGENT_BASE_HPP

class SGAgentBase {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_AGENT_SG_AGENT_BASE_HPP
