
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_AGENT_SG_AGENT_HPP
#define FASTRL_MDP_STOCHASTICGAMES_AGENT_SG_AGENT_HPP

class SGAgent {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_AGENT_SG_AGENT_HPP
