
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_TDMETHODS_VFA_APPROXIMATE_Q_LEARNING_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_TDMETHODS_VFA_APPROXIMATE_Q_LEARNING_HPP

class ApproximateQLearning {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_TDMETHODS_VFA_APPROXIMATE_Q_LEARNING_HPP
