
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_OPTIONS_MACRO_ACTION_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_OPTIONS_MACRO_ACTION_HPP

class MacroAction {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_OPTIONS_MACRO_ACTION_HPP
