
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_OPTIONS_SUBGOAL_OPTION_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_OPTIONS_SUBGOAL_OPTION_HPP

class SubgoalOption {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_OPTIONS_SUBGOAL_OPTION_HPP
