
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_SHELL_COMMAND_ENV_IS_TERMINAL_COMMAND_HPP
#define FASTRL_SHELL_COMMAND_ENV_IS_TERMINAL_COMMAND_HPP

class IsTerminalCommand {

};

#endif //FASTRL_SHELL_COMMAND_ENV_IS_TERMINAL_COMMAND_HPP
