
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_INTERFACES_RLGLUE_RL_GLUE_STATE_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_INTERFACES_RLGLUE_RL_GLUE_STATE_HPP

class RLGlueState {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_INTERFACES_RLGLUE_RL_GLUE_STATE_HPP
