
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_INTERFACES_RLGLUE_RL_GLUE_DOMAIN_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_INTERFACES_RLGLUE_RL_GLUE_DOMAIN_HPP

class RLGlueDomain {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_INTERFACES_RLGLUE_RL_GLUE_DOMAIN_HPP
