
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DATASTRUCTURES_HASHED_AGGREGATOR_HPP
#define FASTRL_DATASTRUCTURES_HASHED_AGGREGATOR_HPP

class HashedAggregator {

};

#endif //FASTRL_DATASTRUCTURES_HASHED_AGGREGATOR_HPP
