
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_RBF_METRICS_EUCLIDEAN_DISTANCE_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_RBF_METRICS_EUCLIDEAN_DISTANCE_HPP

class EuclideanDistance {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_RBF_METRICS_EUCLIDEAN_DISTANCE_HPP
