
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_STATE_ENUMERATOR_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_STATE_ENUMERATOR_HPP

class StateEnumerator {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_STATE_ENUMERATOR_HPP
