
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_STATE_REACHABILITY_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_STATE_REACHABILITY_HPP

class StateReachability {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_STATE_REACHABILITY_HPP
