
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_EXPERIENCEREPLAY_FIXED_SIZE_MEMORY_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_EXPERIENCEREPLAY_FIXED_SIZE_MEMORY_HPP

class FixedSizeMemory {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_EXPERIENCEREPLAY_FIXED_SIZE_MEMORY_HPP
