
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_STOCHASTICGAMES_GRIDGAME_GRID_GAME_STANDARD_MECHANICS_HPP
#define FASTRL_DOMAIN_STOCHASTICGAMES_GRIDGAME_GRID_GAME_STANDARD_MECHANICS_HPP

class GridGameStandardMechanics {

};

#endif //FASTRL_DOMAIN_STOCHASTICGAMES_GRIDGAME_GRID_GAME_STANDARD_MECHANICS_HPP
