
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_MADYNAMICPROGRAMMING_POLICIES_E_CORRELATED_Q_JOINT_POLICY_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_MADYNAMICPROGRAMMING_POLICIES_E_CORRELATED_Q_JOINT_POLICY_HPP

class ECorrelatedQJointPolicy {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_MADYNAMICPROGRAMMING_POLICIES_E_CORRELATED_Q_JOINT_POLICY_HPP
