
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_MADYNAMICPROGRAMMING_POLICIES_E_GREEDY_JOINT_POLICY_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_MADYNAMICPROGRAMMING_POLICIES_E_GREEDY_JOINT_POLICY_HPP

class EGreedyJointPolicy {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_MADYNAMICPROGRAMMING_POLICIES_E_GREEDY_JOINT_POLICY_HPP
