
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_SINGLEAGENT_COMMON_GOAL_BASED_RF_HPP
#define FASTRL_MDP_SINGLEAGENT_COMMON_GOAL_BASED_RF_HPP

class GoalBasedRF {

};

#endif //FASTRL_MDP_SINGLEAGENT_COMMON_GOAL_BASED_RF_HPP
