
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_SINGLEAGENT_COMMON_VISUAL_ACTION_OBSERVER_HPP
#define FASTRL_MDP_SINGLEAGENT_COMMON_VISUAL_ACTION_OBSERVER_HPP

class VisualActionObserver {

};

#endif //FASTRL_MDP_SINGLEAGENT_COMMON_VISUAL_ACTION_OBSERVER_HPP
