
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_LEARNINGRATE_SOFT_TIME_INVERSE_DECAY_LR_HPP
#define FASTRL_BEHAVIOR_LEARNINGRATE_SOFT_TIME_INVERSE_DECAY_LR_HPP

class SoftTimeInverseDecayLR {

};

#endif //FASTRL_BEHAVIOR_LEARNINGRATE_SOFT_TIME_INVERSE_DECAY_LR_HPP
