
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_CARTPOLE_STATES_CART_POLE_STATE_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_CARTPOLE_STATES_CART_POLE_STATE_HPP

class CartPoleState {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_CARTPOLE_STATES_CART_POLE_STATE_HPP
