
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_TWOPLAYER_REPEATEDSINGLESTAGE_GRIM_TRIGGER_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_TWOPLAYER_REPEATEDSINGLESTAGE_GRIM_TRIGGER_HPP

class GrimTrigger {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_TWOPLAYER_REPEATEDSINGLESTAGE_GRIM_TRIGGER_HPP
