
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_TWOPLAYER_REPEATEDSINGLESTAGE_TIT_FOR_TAT_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_TWOPLAYER_REPEATEDSINGLESTAGE_TIT_FOR_TAT_HPP

class TitForTat {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_TWOPLAYER_REPEATEDSINGLESTAGE_TIT_FOR_TAT_HPP
