
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_SOLVERS_CORRELATED_EQUILIBRIUM_SOLVER_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_SOLVERS_CORRELATED_EQUILIBRIUM_SOLVER_HPP

class CorrelatedEquilibriumSolver {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_SOLVERS_CORRELATED_EQUILIBRIUM_SOLVER_HPP
