
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_SOLVERS_MIN_MAX_SOLVER_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_SOLVERS_MIN_MAX_SOLVER_HPP

class MinMaxSolver {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_SOLVERS_MIN_MAX_SOLVER_HPP
