
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_PERFORMANCE_LEARNING_ALGORITHM_EXPERIMENTER_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_PERFORMANCE_LEARNING_ALGORITHM_EXPERIMENTER_HPP

class LearningAlgorithmExperimenter {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_PERFORMANCE_LEARNING_ALGORITHM_EXPERIMENTER_HPP
