
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_APPRENTICESHIP_APPRENTICESHIP_LEARNING_REQUEST_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_APPRENTICESHIP_APPRENTICESHIP_LEARNING_REQUEST_HPP

class ApprenticeshipLearningRequest {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_APPRENTICESHIP_APPRENTICESHIP_LEARNING_REQUEST_HPP
