
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_INTERFACING_SINGLEAGENT_LEARNING_AGENT_TO_SG_AGENT_INTERFACE_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_INTERFACING_SINGLEAGENT_LEARNING_AGENT_TO_SG_AGENT_INTERFACE_HPP

class LearningAgentToSGAgentInterface {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_INTERFACING_SINGLEAGENT_LEARNING_AGENT_TO_SG_AGENT_INTERFACE_HPP
