
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_STOCHASTICGAMES_GRIDGAME_STATE_GG_AGENT_HPP
#define FASTRL_DOMAIN_STOCHASTICGAMES_GRIDGAME_STATE_GG_AGENT_HPP

class GGAgent {

};

#endif //FASTRL_DOMAIN_STOCHASTICGAMES_GRIDGAME_STATE_GG_AGENT_HPP
