
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_STATEHASHING_DISCRETIZED_DISC_CONFIG_HPP
#define FASTRL_STATEHASHING_DISCRETIZED_DISC_CONFIG_HPP

class DiscConfig {

};

#endif //FASTRL_STATEHASHING_DISCRETIZED_DISC_CONFIG_HPP
