
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_STATEHASHING_DISCRETIZED_DISCRETIZING_HASHABLE_STATE_FACTORY_HPP
#define FASTRL_STATEHASHING_DISCRETIZED_DISCRETIZING_HASHABLE_STATE_FACTORY_HPP

class DiscretizingHashableStateFactory {

};

#endif //FASTRL_STATEHASHING_DISCRETIZED_DISCRETIZING_HASHABLE_STATE_FACTORY_HPP
