
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_STATEHASHING_DISCRETIZED_II_DISC_HASHABLE_STATE_HPP
#define FASTRL_STATEHASHING_DISCRETIZED_II_DISC_HASHABLE_STATE_HPP

class IIDiscHashableState {

};

#endif //FASTRL_STATEHASHING_DISCRETIZED_II_DISC_HASHABLE_STATE_HPP
