
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SUPERVISED_SUPERVISED_VFA_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SUPERVISED_SUPERVISED_VFA_HPP

class SupervisedVFA {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SUPERVISED_SUPERVISED_VFA_HPP
