
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_LEARNING_AGENT_FACTORY_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_LEARNING_AGENT_FACTORY_HPP

class LearningAgentFactory {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_LEARNING_AGENT_FACTORY_HPP
