
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_NAIVEQ_SG_NAIVE_Q_FACTORY_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_NAIVEQ_SG_NAIVE_Q_FACTORY_HPP

class SGNaiveQFactory {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_NAIVEQ_SG_NAIVE_Q_FACTORY_HPP
