
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_NAIVEQ_SG_NAIVE_QL_AGENT_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_NAIVEQ_SG_NAIVE_QL_AGENT_HPP

class SGNaiveQLAgent {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_NAIVEQ_SG_NAIVE_QL_AGENT_HPP
