
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_LINEAR_VFA_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_LINEAR_VFA_HPP

class LinearVFA {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_LINEAR_VFA_HPP
