
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_SPARSE_CROSS_PRODUCT_FEATURES_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_SPARSE_CROSS_PRODUCT_FEATURES_HPP

class SparseCrossProductFeatures {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_SPARSE_CROSS_PRODUCT_FEATURES_HPP
