
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_STATE_FEATURE_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_STATE_FEATURE_HPP

class StateFeature {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_STATE_FEATURE_HPP
