
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_CARTPOLE_MODEL_CP_CLASSIC_MODEL_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_CARTPOLE_MODEL_CP_CLASSIC_MODEL_HPP

class CPClassicModel {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_CARTPOLE_MODEL_CP_CLASSIC_MODEL_HPP
