
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_CARTPOLE_MODEL_IP_MODEL_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_CARTPOLE_MODEL_IP_MODEL_HPP

class IPModel {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_CARTPOLE_MODEL_IP_MODEL_HPP
