
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_DIFFERENTIABLEPLANNERS_DIFFVINIT_DIFF_VFRF_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_DIFFERENTIABLEPLANNERS_DIFFVINIT_DIFF_VFRF_HPP

class DiffVFRF {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_DIFFERENTIABLEPLANNERS_DIFFVINIT_DIFF_VFRF_HPP
