
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_DIFFERENTIABLEPLANNERS_DIFFVINIT_VANILLA_DIFF_VINIT_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_DIFFERENTIABLEPLANNERS_DIFFVINIT_VANILLA_DIFF_VINIT_HPP

class VanillaDiffVinit {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_DIFFERENTIABLEPLANNERS_DIFFVINIT_VANILLA_DIFF_VINIT_HPP
