
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_AUXILIARY_STATECONDITIONTEST_SINGLE_PFSCT_HPP
#define FASTRL_MDP_AUXILIARY_STATECONDITIONTEST_SINGLE_PFSCT_HPP

class SinglePFSCT {

};

#endif //FASTRL_MDP_AUXILIARY_STATECONDITIONTEST_SINGLE_PFSCT_HPP
