
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_AUXILIARY_STATECONDITIONTEST_STATE_CONDITION_TEST_ITERABLE_HPP
#define FASTRL_MDP_AUXILIARY_STATECONDITIONTEST_STATE_CONDITION_TEST_ITERABLE_HPP

class StateConditionTestIterable {

};

#endif //FASTRL_MDP_AUXILIARY_STATECONDITIONTEST_STATE_CONDITION_TEST_ITERABLE_HPP
