
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_CONCATENATED_OBJECT_FEATURES_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_CONCATENATED_OBJECT_FEATURES_HPP

class ConcatenatedObjectFeatures {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_CONCATENATED_OBJECT_FEATURES_HPP
