
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_DENSE_CROSS_PRODUCT_FEATURES_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_DENSE_CROSS_PRODUCT_FEATURES_HPP

class DenseCrossProductFeatures {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_DENSE_CROSS_PRODUCT_FEATURES_HPP
