
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_DENSE_STATE_ACTION_LINEAR_VFA_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_DENSE_STATE_ACTION_LINEAR_VFA_HPP

class DenseStateActionLinearVFA {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_DENSE_STATE_ACTION_LINEAR_VFA_HPP
