
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_NUMERIC_VARIABLE_FEATURES_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_NUMERIC_VARIABLE_FEATURES_HPP

class NumericVariableFeatures {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_NUMERIC_VARIABLE_FEATURES_HPP
