
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_SPARSE_TO_DENSE_FEATURES_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_SPARSE_TO_DENSE_FEATURES_HPP

class SparseToDenseFeatures {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_SPARSE_TO_DENSE_FEATURES_HPP
