
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_RBF_DISTANCE_METRIC_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_RBF_DISTANCE_METRIC_HPP

class DistanceMetric {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DENSE_RBF_DISTANCE_METRIC_HPP
