
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_WORLD_WORLD_HPP
#define FASTRL_MDP_STOCHASTICGAMES_WORLD_WORLD_HPP

class World {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_WORLD_WORLD_HPP
