
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_WORLD_WORLD_OBSERVER_HPP
#define FASTRL_MDP_STOCHASTICGAMES_WORLD_WORLD_OBSERVER_HPP

class WorldObserver {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_WORLD_WORLD_OBSERVER_HPP
