
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_SINGLEAGENT_MODEL_DELEGATED_MODEL_HPP
#define FASTRL_MDP_SINGLEAGENT_MODEL_DELEGATED_MODEL_HPP

class DelegatedModel {

};

#endif //FASTRL_MDP_SINGLEAGENT_MODEL_DELEGATED_MODEL_HPP
