
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_STATEHASHING_MASKEDDISCRETIZED_DISC_MASKED_CONFIG_HPP
#define FASTRL_STATEHASHING_MASKEDDISCRETIZED_DISC_MASKED_CONFIG_HPP

class DiscMaskedConfig {

};

#endif //FASTRL_STATEHASHING_MASKEDDISCRETIZED_DISC_MASKED_CONFIG_HPP
