
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_CARTPOLE_INVERTED_PENDULUM_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_CARTPOLE_INVERTED_PENDULUM_HPP

class InvertedPendulum {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_CARTPOLE_INVERTED_PENDULUM_HPP
