
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_POMDP_BELIEF_POLICY_AGENT_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_POMDP_BELIEF_POLICY_AGENT_HPP

class BeliefPolicyAgent {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_POMDP_BELIEF_POLICY_AGENT_HPP
