
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_SINGLEAGENT_POMDP_OBSERVATIONS_OBSERVATION_PROBABILITY_HPP
#define FASTRL_MDP_SINGLEAGENT_POMDP_OBSERVATIONS_OBSERVATION_PROBABILITY_HPP

class ObservationProbability {

};

#endif //FASTRL_MDP_SINGLEAGENT_POMDP_OBSERVATIONS_OBSERVATION_PROBABILITY_HPP
