
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_SINGLEAGENT_POMDP_OBSERVATIONS_OBSERVATION_FUNCTION_HPP
#define FASTRL_MDP_SINGLEAGENT_POMDP_OBSERVATIONS_OBSERVATION_FUNCTION_HPP

class ObservationFunction {

};

#endif //FASTRL_MDP_SINGLEAGENT_POMDP_OBSERVATIONS_OBSERVATION_FUNCTION_HPP
