
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_SHELL_COMMAND_WORLD_LAST_JOINT_ACTION_COMMAND_HPP
#define FASTRL_SHELL_COMMAND_WORLD_LAST_JOINT_ACTION_COMMAND_HPP

class LastJointActionCommand {

};

#endif //FASTRL_SHELL_COMMAND_WORLD_LAST_JOINT_ACTION_COMMAND_HPP
