
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_SHELL_COMMAND_WORLD_REMOVE_STATE_OBJECT_SG_COMMAND_HPP
#define FASTRL_SHELL_COMMAND_WORLD_REMOVE_STATE_OBJECT_SG_COMMAND_HPP

class RemoveStateObjectSGCommand {

};

#endif //FASTRL_SHELL_COMMAND_WORLD_REMOVE_STATE_OBJECT_SG_COMMAND_HPP
