
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_SHELL_COMMAND_WORLD_WORLD_OBSERVATION_COMMAND_HPP
#define FASTRL_SHELL_COMMAND_WORLD_WORLD_OBSERVATION_COMMAND_HPP

class WorldObservationCommand {

};

#endif //FASTRL_SHELL_COMMAND_WORLD_WORLD_OBSERVATION_COMMAND_HPP
