
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_CORE_STATE_ANNOTATIONS_DEEP_COPY_STATE_HPP
#define FASTRL_MDP_CORE_STATE_ANNOTATIONS_DEEP_COPY_STATE_HPP

class DeepCopyState {

};

#endif //FASTRL_MDP_CORE_STATE_ANNOTATIONS_DEEP_COPY_STATE_HPP
