
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_ACTORCRITIC_CRITICS_TD_LAMBDA_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_ACTORCRITIC_CRITICS_TD_LAMBDA_HPP

class TDLambda {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_ACTORCRITIC_CRITICS_TD_LAMBDA_HPP
