
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_POLICY_SUPPORT_POLICY_UNDEFINED_EXCEPTION_HPP
#define FASTRL_BEHAVIOR_POLICY_SUPPORT_POLICY_UNDEFINED_EXCEPTION_HPP

class PolicyUndefinedException {

};

#endif //FASTRL_BEHAVIOR_POLICY_SUPPORT_POLICY_UNDEFINED_EXCEPTION_HPP
