
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_MOUNTAINCAR_MC_RANDOM_STATE_GENERATOR_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_MOUNTAINCAR_MC_RANDOM_STATE_GENERATOR_HPP

class MCRandomStateGenerator {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_MOUNTAINCAR_MC_RANDOM_STATE_GENERATOR_HPP
