
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_MOUNTAINCAR_MOUNTAIN_CAR_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_MOUNTAINCAR_MOUNTAIN_CAR_HPP

class MountainCar {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_MOUNTAINCAR_MOUNTAIN_CAR_HPP
