
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_AUXILIARY_COMMON_GOAL_CONDITION_TF_HPP
#define FASTRL_MDP_AUXILIARY_COMMON_GOAL_CONDITION_TF_HPP

class GoalConditionTF {

};

#endif //FASTRL_MDP_AUXILIARY_COMMON_GOAL_CONDITION_TF_HPP
