
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_AUXILIARY_COMMON_IDENTITY_STATE_MAPPING_HPP
#define FASTRL_MDP_AUXILIARY_COMMON_IDENTITY_STATE_MAPPING_HPP

class IdentityStateMapping {

};

#endif //FASTRL_MDP_AUXILIARY_COMMON_IDENTITY_STATE_MAPPING_HPP
