
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_AUXILIARY_COMMON_RANDOM_START_STATE_GENERATOR_HPP
#define FASTRL_MDP_AUXILIARY_COMMON_RANDOM_START_STATE_GENERATOR_HPP

class RandomStartStateGenerator {

};

#endif //FASTRL_MDP_AUXILIARY_COMMON_RANDOM_START_STATE_GENERATOR_HPP
