
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_AUXILIARY_COMMON_SINGLE_PFTF_HPP
#define FASTRL_MDP_AUXILIARY_COMMON_SINGLE_PFTF_HPP

class SinglePFTF {

};

#endif //FASTRL_MDP_AUXILIARY_COMMON_SINGLE_PFTF_HPP
