
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_LSPI_LSPI_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_LSPI_LSPI_HPP

class LSPI {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_LSPI_LSPI_HPP
