
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_LSPI_SARS_COLLECTOR_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_LSPI_SARS_COLLECTOR_HPP

class SARSCollector {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_LSPI_SARS_COLLECTOR_HPP
