
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_TOURNAMENT_MATCH_ENTRY_HPP
#define FASTRL_MDP_STOCHASTICGAMES_TOURNAMENT_MATCH_ENTRY_HPP

class MatchEntry {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_TOURNAMENT_MATCH_ENTRY_HPP
