
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_TOURNAMENT_TOURNAMENT_HPP
#define FASTRL_MDP_STOCHASTICGAMES_TOURNAMENT_TOURNAMENT_HPP

class Tournament {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_TOURNAMENT_TOURNAMENT_HPP
