
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_STOCHASTIC_MONTECARLO_UCT_UCT_ACTION_NODE_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_STOCHASTIC_MONTECARLO_UCT_UCT_ACTION_NODE_HPP

class UCTActionNode {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_STOCHASTIC_MONTECARLO_UCT_UCT_ACTION_NODE_HPP
