
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_LUNARLANDER_STATE_LL_STATE_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_LUNARLANDER_STATE_LL_STATE_HPP

class LLState {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_LUNARLANDER_STATE_LL_STATE_HPP
