
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_SINGLEAGENT_OO_OBJECT_PARAMETERIZED_ACTION_TYPE_HPP
#define FASTRL_MDP_SINGLEAGENT_OO_OBJECT_PARAMETERIZED_ACTION_TYPE_HPP

class ObjectParameterizedActionType {

};

#endif //FASTRL_MDP_SINGLEAGENT_OO_OBJECT_PARAMETERIZED_ACTION_TYPE_HPP
