
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_OPTIONS_MODEL_BFS_NON_MARKOV_OPTION_MODEL_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_OPTIONS_MODEL_BFS_NON_MARKOV_OPTION_MODEL_HPP

class BFSNonMarkovOptionModel {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_OPTIONS_MODEL_BFS_NON_MARKOV_OPTION_MODEL_HPP
