
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_STATEHASHING_MASKED_ID_MASKED_HASHABLE_STATE_HPP
#define FASTRL_STATEHASHING_MASKED_ID_MASKED_HASHABLE_STATE_HPP

class IDMaskedHashableState {

};

#endif //FASTRL_STATEHASHING_MASKED_ID_MASKED_HASHABLE_STATE_HPP
