
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_GRAPHDEFINED_GRAPH_DEFINED_DOMAIN_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_GRAPHDEFINED_GRAPH_DEFINED_DOMAIN_HPP

class GraphDefinedDomain {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_GRAPHDEFINED_GRAPH_DEFINED_DOMAIN_HPP
