
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_GRAPHDEFINED_GRAPH_STATE_NODE_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_GRAPHDEFINED_GRAPH_STATE_NODE_HPP

class GraphStateNode {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_GRAPHDEFINED_GRAPH_STATE_NODE_HPP
