
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_POLICY_GREEDY_DETERMINISTIC_Q_POLICY_HPP
#define FASTRL_BEHAVIOR_POLICY_GREEDY_DETERMINISTIC_Q_POLICY_HPP

class GreedyDeterministicQPolicy {

};

#endif //FASTRL_BEHAVIOR_POLICY_GREEDY_DETERMINISTIC_Q_POLICY_HPP
