
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_STATEHASHING_SIMPLE_II_SIMPLE_HASHABLE_STATE_HPP
#define FASTRL_STATEHASHING_SIMPLE_II_SIMPLE_HASHABLE_STATE_HPP

class IISimpleHashableState {

};

#endif //FASTRL_STATEHASHING_SIMPLE_II_SIMPLE_HASHABLE_STATE_HPP
