
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_STATEHASHING_SIMPLE_SIMPLE_HASHABLE_STATE_FACTORY_HPP
#define FASTRL_STATEHASHING_SIMPLE_SIMPLE_HASHABLE_STATE_FACTORY_HPP

class SimpleHashableStateFactory {

};

#endif //FASTRL_STATEHASHING_SIMPLE_SIMPLE_HASHABLE_STATE_FACTORY_HPP
