
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_MODELLEARNING_LEARNED_MODEL_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_MODELLEARNING_LEARNED_MODEL_HPP

class LearnedModel {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNING_MODELLEARNING_LEARNED_MODEL_HPP
