
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_TILECODING_TILE_CODING_FEATURES_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_TILECODING_TILE_CODING_FEATURES_HPP

class TileCodingFeatures {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_TILECODING_TILE_CODING_FEATURES_HPP
