
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_TILECODING_TILING_ARRANGEMENT_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_TILECODING_TILING_ARRANGEMENT_HPP

class TilingArrangement {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_SPARSE_TILECODING_TILING_ARRANGEMENT_HPP
