
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_RANDOM_SG_AGENT_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_RANDOM_SG_AGENT_HPP

class RandomSGAgent {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_RANDOM_SG_AGENT_HPP
