
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_COMMON_AGENT_FACTORY_WITH_SUBJECTIVE_REWARD_HPP
#define FASTRL_MDP_STOCHASTICGAMES_COMMON_AGENT_FACTORY_WITH_SUBJECTIVE_REWARD_HPP

class AgentFactoryWithSubjectiveReward {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_COMMON_AGENT_FACTORY_WITH_SUBJECTIVE_REWARD_HPP
