
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_COMMON_NULL_JOINT_REWARD_FUNCTION_HPP
#define FASTRL_MDP_STOCHASTICGAMES_COMMON_NULL_JOINT_REWARD_FUNCTION_HPP

class NullJointRewardFunction {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_COMMON_NULL_JOINT_REWARD_FUNCTION_HPP
