
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_COMMON_STATIC_REPEATED_GAME_MODEL_HPP
#define FASTRL_MDP_STOCHASTICGAMES_COMMON_STATIC_REPEATED_GAME_MODEL_HPP

class StaticRepeatedGameModel {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_COMMON_STATIC_REPEATED_GAME_MODEL_HPP
