
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_GRIDWORLD_GRID_WORLD_REWARD_FUNCTION_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_GRIDWORLD_GRID_WORLD_REWARD_FUNCTION_HPP

class GridWorldRewardFunction {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_GRIDWORLD_GRID_WORLD_REWARD_FUNCTION_HPP
