
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_BLOCKSWORLD_BLOCKS_WORLD_BLOCK_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_BLOCKSWORLD_BLOCKS_WORLD_BLOCK_HPP

class BlocksWorldBlock {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_BLOCKSWORLD_BLOCKS_WORLD_BLOCK_HPP
