
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_BLOCKSWORLD_BLOCKS_WORLD_STATE_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_BLOCKSWORLD_BLOCKS_WORLD_STATE_HPP

class BlocksWorldState {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_BLOCKSWORLD_BLOCKS_WORLD_STATE_HPP
