
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_BLOCKSWORLD_BW_MODEL_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_BLOCKSWORLD_BW_MODEL_HPP

class BWModel {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_BLOCKSWORLD_BW_MODEL_HPP
