
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_TWOPLAYER_SINGLESTAGE_EQUILIBRIUMPLAYER_EQUILIBRIUM_PLAYING_SG_AGENT_HPP
#define FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_TWOPLAYER_SINGLESTAGE_EQUILIBRIUMPLAYER_EQUILIBRIUM_PLAYING_SG_AGENT_HPP

class EquilibriumPlayingSGAgent {

};

#endif //FASTRL_BEHAVIOR_STOCHASTICGAMES_AGENTS_TWOPLAYER_SINGLESTAGE_EQUILIBRIUMPLAYER_EQUILIBRIUM_PLAYING_SG_AGENT_HPP
