/*
 * Mark Benjamin 06 March 2019.
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DIFFERENTIABLE_STATE_ACTION_VALUE_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DIFFERENTIABLE_STATE_ACTION_VALUE_HPP

#include "parametric_function.hpp"

class DifferentiableStateActionValue : public ParametricStateActionFunction {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_DIFFERENTIABLE_STATE_ACTION_VALUE_HPP
