
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_FUNCTION_GRADIENT_HPP
#define FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_FUNCTION_GRADIENT_HPP

class FunctionGradient {

};

#endif //FASTRL_BEHAVIOR_FUNCTIONAPPROXIMATION_FUNCTION_GRADIENT_HPP
