
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_STOCHASTICGAMES_MODEL_JOINT_REWARD_FUNCTION_HPP
#define FASTRL_MDP_STOCHASTICGAMES_MODEL_JOINT_REWARD_FUNCTION_HPP

class JointRewardFunction {

};

#endif //FASTRL_MDP_STOCHASTICGAMES_MODEL_JOINT_REWARD_FUNCTION_HPP
