
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_LUNARLANDER_LUNAR_LANDER_TF_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_LUNARLANDER_LUNAR_LANDER_TF_HPP

class LunarLanderTF {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_LUNARLANDER_LUNAR_LANDER_TF_HPP
