
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_LUNARLANDER_LUNAR_LANDER_RF_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_LUNARLANDER_LUNAR_LANDER_RF_HPP

class LunarLanderRF {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_LUNARLANDER_LUNAR_LANDER_RF_HPP
