
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_VFA_FITTEDVI_FITTED_VI_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_VFA_FITTEDVI_FITTED_VI_HPP

class FittedVI {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_PLANNING_VFA_FITTEDVI_FITTED_VI_HPP
