
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_COMMONRFS_LINEAR_STATE_ACTION_DIFFERENTIABLE_RF_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_COMMONRFS_LINEAR_STATE_ACTION_DIFFERENTIABLE_RF_HPP

class LinearStateActionDifferentiableRF {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_COMMONRFS_LINEAR_STATE_ACTION_DIFFERENTIABLE_RF_HPP
