
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_CORE_OO_STATE_EXCEPTIONS_UNKNOWN_CLASS_EXCEPTION_HPP
#define FASTRL_MDP_CORE_OO_STATE_EXCEPTIONS_UNKNOWN_CLASS_EXCEPTION_HPP

class UnknownClassException {

};

#endif //FASTRL_MDP_CORE_OO_STATE_EXCEPTIONS_UNKNOWN_CLASS_EXCEPTION_HPP
