
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_DIFFERENTIABLEPLANNERS_DIFFERENTIABLE_SPARSE_SAMPLING_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_DIFFERENTIABLEPLANNERS_DIFFERENTIABLE_SPARSE_SAMPLING_HPP

class DifferentiableSparseSampling {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_DIFFERENTIABLEPLANNERS_DIFFERENTIABLE_SPARSE_SAMPLING_HPP
