
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_DIFFERENTIABLEPLANNERS_DIFFERENTIABLE_VI_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_DIFFERENTIABLEPLANNERS_DIFFERENTIABLE_VI_HPP

class DifferentiableVI {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_DIFFERENTIABLEPLANNERS_DIFFERENTIABLE_VI_HPP
