
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_SUPPORT_BOLTZMANN_POLICY_GRADIENT_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_SUPPORT_BOLTZMANN_POLICY_GRADIENT_HPP

class BoltzmannPolicyGradient {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_SUPPORT_BOLTZMANN_POLICY_GRADIENT_HPP
