
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_SUPPORT_DIFFERENTIABLE_Q_FUNCTION_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_SUPPORT_DIFFERENTIABLE_Q_FUNCTION_HPP

class DifferentiableQFunction {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_SUPPORT_DIFFERENTIABLE_Q_FUNCTION_HPP
