
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_SUPPORT_DIFFERENTIABLE_VALUE_FUNCTION_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_SUPPORT_DIFFERENTIABLE_VALUE_FUNCTION_HPP

class DifferentiableValueFunction {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_LEARNFROMDEMO_MLIRL_SUPPORT_DIFFERENTIABLE_VALUE_FUNCTION_HPP
