
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_GRIDSET_FLAT_STATE_GRIDDER_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_GRIDSET_FLAT_STATE_GRIDDER_HPP

class FlatStateGridder {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_GRIDSET_FLAT_STATE_GRIDDER_HPP
