
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_GRIDSET_VARIABLE_GRID_SPEC_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_GRIDSET_VARIABLE_GRID_SPEC_HPP

class VariableGridSpec {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_AUXILIARY_GRIDSET_VARIABLE_GRID_SPEC_HPP
