
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_POMDP_TIGER_TIGER_OBSERVATION_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_POMDP_TIGER_TIGER_OBSERVATION_HPP

class TigerObservation {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_POMDP_TIGER_TIGER_OBSERVATION_HPP
