
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_BLOCKDUDE_BLOCK_DUDE_MODEL_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_BLOCKDUDE_BLOCK_DUDE_MODEL_HPP

class BlockDudeModel {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_BLOCKDUDE_BLOCK_DUDE_MODEL_HPP
