
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_BLOCKDUDE_BLOCK_DUDE_TF_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_BLOCKDUDE_BLOCK_DUDE_TF_HPP

class BlockDudeTF {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_BLOCKDUDE_BLOCK_DUDE_TF_HPP
