
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_DOMAIN_SINGLEAGENT_RLGLUE_RL_GLUE_ENVIRONMENT_HPP
#define FASTRL_DOMAIN_SINGLEAGENT_RLGLUE_RL_GLUE_ENVIRONMENT_HPP

class RLGlueEnvironment {

};

#endif //FASTRL_DOMAIN_SINGLEAGENT_RLGLUE_RL_GLUE_ENVIRONMENT_HPP
