
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_BEHAVIOR_SINGLEAGENT_POMDP_WRAPPEDMDPALGS_BELIEF_SPARSE_SAMPLING_HPP
#define FASTRL_BEHAVIOR_SINGLEAGENT_POMDP_WRAPPEDMDPALGS_BELIEF_SPARSE_SAMPLING_HPP

class BeliefSparseSampling {

};

#endif //FASTRL_BEHAVIOR_SINGLEAGENT_POMDP_WRAPPEDMDPALGS_BELIEF_SPARSE_SAMPLING_HPP
