
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_SINGLEAGENT_POMDP_BELIEFSTATE_BELIEF_STATE_HPP
#define FASTRL_MDP_SINGLEAGENT_POMDP_BELIEFSTATE_BELIEF_STATE_HPP

class BeliefState {

};

#endif //FASTRL_MDP_SINGLEAGENT_POMDP_BELIEFSTATE_BELIEF_STATE_HPP
