
/*
 * Mark Benjamin 6th March 2019
 * Copyright (c) 2019 Mark Benjamin
 */

#ifndef FASTRL_MDP_SINGLEAGENT_POMDP_BELIEFSTATE_DENSE_BELIEF_VECTOR_HPP
#define FASTRL_MDP_SINGLEAGENT_POMDP_BELIEFSTATE_DENSE_BELIEF_VECTOR_HPP

class DenseBeliefVector {

};

#endif //FASTRL_MDP_SINGLEAGENT_POMDP_BELIEFSTATE_DENSE_BELIEF_VECTOR_HPP
